<tr class="setting-banlist" id="invoice_<?php echo $wo['invoiceInfo']->id?>" >
    <td><?php echo $wo['invoiceInfo']->id?></td>
    <td>
        <div>
            <a href="/<?=$wo['invoiceInfo']->username?>"><?= $wo['invoiceInfo']->username;?></a>
        </div>
    </td>
    <td>
        <?php echo $wo['invoiceInfo']->product_title; ?>
    </td>
    <td>
        <?php echo $wo['invoiceInfo']->product_price;?>
    </td>
    <td>
        <?php echo $wo['invoiceInfo']->qty;?>
    </td>
    <td>
        <a href="/<?=$wo['invoiceInfo']->file?>" target="_blank" class="btn btn-success waves-effect">Download</a>
        <input class="multi-download" type="checkbox" name="file[<?=$wo['invoiceInfo']->id?>]" value="<?=$wo['invoiceInfo']->id?>" onchange="enable_dwnld_btn()">
    </td>
    <td>
        <a href="javascript:void()" onclick="delete_invoice('<?php echo $wo['invoiceInfo']->id; ?>')" class="btn btn-danger waves-effect">DELETE</a>
    </td>
</tr>
<script>
    function enable_dwnld_btn() {
        let checkBoxses         = document.querySelectorAll(".multi-download:checked");
        let multi_downlod_btn   = document.getElementsByClassName('multi-downld-btn')[0];
        if(checkBoxses.length > 0) {
            multi_downlod_btn.classList.remove("disabled");
        }else{
            if(!multi_downlod_btn.classList.contains("disabled")){
                multi_downlod_btn.classList.add("disabled");
            }
        }
    }
</script>